sender_email_address = "mail@example.com"
student_address_template = "{}@epita.fr"
email_subject = "<Mail Subject>"

[smtp]  # Required for SEND mode only
host = "<smtp host address>"
port = 587
user = "mail@example.com"
password = "********"
